Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.network "forwarded_port", guest: 3000, host: 3052
  config.vm.synced_folder ".", "/Users/kislak/laboratory/otus/linux_admin/000_rails/project"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
  end

  config.vm.provision 'shell', path: 'provision.sh'
end
