# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "ubuntu_2004" do |server|
    config.vm.box = 'bento/ubuntu-20.04'
   # config.vm.network "private_network", type: "dhcp"
  end

  config.vm.define "centos_7" do |server|
    config.vm.box = "bento/centos-7"
   # config.vm.network "private_network", type: "dhcp"
  end

  # https://github.com/mitchellh/vagrant-google

  # config.vm.define "ks2" do |server|
  #   config.vm.box = 'ubuntu/20.04'
  # end
  #
  #
  # config.vm.define "ks3" do |server|
  #   config.vm.box = 'ubuntu/20.04'
  # end
end
