Vagrant.configure("2") do |config|
  config.vm.define "server" do |server_config|
    server_config.vm.box = "bento/ubuntu-20.04"
    server_config.vm.hostname = "server"
  end

  config.vm.define "client" do |client_config|
    client_config.vm.box = "bento/ubuntu-20.04"
    client_config.vm.hostname = "client"
  end

  config.vm.define "client2" do |client_config|
    client_config.vm.box = "bento/ubuntu-20.04"
    client_config.vm.hostname = "client2"
  end
end
