# -*- mode: ruby -*-
# vi: set ft=ruby :


PROVISION_SCRIPT = <<SCRIPT
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "google/gce"
  config.vm.provision :shell, path: "provision.sh"

  config.vm.provider :google do |google, override|
    # other options: https://github.com/mitchellh/vagrant-google

    # ssh-keygen -t rsa -f google_compute_engine -C vagrant
    # https://console.cloud.google.com/compute/metadata
    override.ssh.username = "vagrant"
    override.ssh.private_key_path = "google_compute_engine"

    google.google_project_id = "hardfunart"
    google.google_json_key_location = "private-key.json" # service account, JSON key, download

    google.name = "vagrant01"
    google.zone = "europe-west4-b" # https://cloud.google.com/compute/docs/regions-zones
    google.machine_type = "e2-standard-8" # https://cloud.google.com/compute/docs/machine-types
    google.image_family = "ubuntu-2004-lts"

    google.tags = ['http-server']
  end
end
