# -*- mode: ruby -*-
# vi: set ft=ruby :


PROVISION_SCRIPT = <<SCRIPT
uname=$(uname -a)
ver=$(cat /etc/debian_version)
echo "== BEGIN: vagrant provisioning on '${uname}'"
echo "== DEBIAN VERSION: ${ver}"
echo "== UPDATING repositories and packages"
/usr/bin/apt-get update -y -qq > /dev/null 2>&1
/usr/bin/apt-get upgrade -y -qq > /dev/null 2>&1
extip=$(curl -s http://metadata/computeMetadata/v1/instance/network-interfaces/0/access-configs/0/external-ip -H "Metadata-Flavor: Google")
echo "== EXTERNAL IP: ${extip}"
echo "== APPENDING /etc/motd"
d=$(date +%r)
echo "# ${d}" >> /etc/motd
echo "== cat /etc/motd"
cat /etc/motd
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "google/gce"
  config.vm.provision :shell, inline: PROVISION_SCRIPT

  config.vm.provider :google do |google, override|
    # other options: https://github.com/mitchellh/vagrant-google
    google.google_project_id = "hardfunart"
    google.google_json_key_location = "./private-key.json" # service account, JSON key, download

    google.name = "vagrant01"
    google.zone = "europe-west4-b" # https://cloud.google.com/compute/docs/regions-zones
    google.machine_type = "e2-standard-8" # https://cloud.google.com/compute/docs/machine-types
    google.image_family = "ubuntu-2004-lts"

    # ssh-keygen -t rsa -f google_compute_engine -C vagrant
    # https://console.cloud.google.com/compute/metadata
    override.ssh.username = "vagrant"
    override.ssh.private_key_path = "./google_compute_engine"
  end
end
