Vagrant.configure("2") do |config|
  config.vm.define "server" do |server_config|
    server_config.vm.box = "centos/8"
    server_config.vm.hostname = "server"
  end
  
  config.vm.define "client" do |client_config|
    client_config.vm.box = "centos/8"
    client_config.vm.hostname = "client"
  end 
end
