# -*- mode: ruby -*-
# vim: set ft=ruby :

ENV['LC_ALL'] = 'en_US.UTF-8'


HOME_DIR = '.'
DISKS = [
  {
    file: HOME_DIR + '/VirtualBox VMs/sata1.vdi',
    size: 10_240, # Megabytes
    port: 1
  },
  {
    file: HOME_DIR + '/VirtualBox VMs/sata2.vdi',
    size: 2048,
    port: 2
  },
  {
    file: HOME_DIR + '/VirtualBox VMs/sata3.vdi',
    size: 1024,
    port: 3
  },
  {
    file: HOME_DIR + '/VirtualBox VMs/sata4.vdi',
    size: 1024,
    port: 4
  }
]


Vagrant.configure('2') do |config|
  config.vm.define 'lvm' do |box|
    box.vm.box = 'centos/7'
    box.vm.box_version = '1804.02'
    box.vm.host_name = 'lvm'
    box.vm.network 'private_network', ip: '192.168.11.101'

    box.vm.provider :virtualbox do |vb|
      vb.customize [
        'modifyvm', :id,
        '--memory', '1024'
      ]

      DISKS.each do |disk|
        next if File.exist?(disk[:file])

        vb.customize [
          'createhd',
          '--filename', disk[:file],
          '--variant', 'Fixed',
          '--size', disk[:size]
        ]
      end

      unless File.exist?(DISKS.first[:file])
        vb.customize [
          'storagectl', :id,
          '--name', 'SATA',
          '--add', 'sata'
        ]
      end

      DISKS.each do |disk|
        vb.customize [
          'storageattach', :id,
          '--storagectl', 'SATA',
          '--port', disk[:port],
          '--device', 0,
          '--type', 'hdd',
          '--medium', disk[:file]
        ]
      end
    end

    box.vm.provision 'shell', path: 'script.sh'
  end
end
