# -*- mode: ruby -*-
# vim: set ft=ruby :

home = '.'
ENV['LC_ALL'] = 'en_US.UTF-8'

MACHINES = {
  lvm: {
    box_name: 'centos/7',
    box_version: '1804.02',
    ip_addr: '192.168.11.101',
    disks: [
      {
        dfile: home + '/VirtualBox VMs/sata1.vdi',
        size: 10_240,
        port: 1
      },
      {
        dfile: home + '/VirtualBox VMs/sata2.vdi',
        size: 2048, # Megabytes
        port: 2
      },
      {
        dfile: home + '/VirtualBox VMs/sata3.vdi',
        size: 1024, # Megabytes
        port: 3
      },
      {
        dfile: home + '/VirtualBox VMs/sata4.vdi',
        size: 1024,
        port: 4
      }
    ]
  }
}.freeze

Vagrant.configure('2') do |config|
  MACHINES.each do |boxname, boxconfig|
    config.vm.box_version = boxconfig[:box_version]
    config.vm.define boxname do |box|
      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxname.to_s
      box.vm.network 'private_network', ip: boxconfig[:ip_addr]

      box.vm.provider :virtualbox do |vb|
        vb.customize [
          'modifyvm', :id,
          '--memory', '1024'
        ]

        boxconfig[:disks].each do |disk|
          next if File.exist?(disk[:dfile])

          vb.customize [
            'createhd',
            '--filename', disk[:dfile],
            '--variant', 'Fixed',
            '--size', disk[:size]
          ]
        end

        unless File.exist?(boxconfig[:disks].first[:dfile])
          vb.customize [
            'storagectl', :id,
            '--name', 'SATA',
            '--add', 'sata'
          ]
        end

        boxconfig[:disks].each do |disk|
          vb.customize [
            'storageattach', :id,
            '--storagectl', 'SATA',
            '--port', disk[:port],
            '--device', 0,
            '--type', 'hdd',
            '--medium', disk[:dfile]
          ]
        end
      end

      box.vm.provision 'shell', path: 'script.sh'
    end
  end
end
